#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: 1.4.2 RELEASE

settings:
  # Safe-mode determines if scoreboard is synchronized with the server (true) or asynchronized (false)
  # Synchronized (safe-mode: true) is more stable and robust
  # Asynchronized (safe-mode: false) is more faster but can cause strange problems in some cases
  safe-mode: false
  # If the server version is 1.13 or higher, enable longline.
  # true: you can use 128 characters per line (1.13 and up)
  # false: you can use 32 characters per line (1.12 and down)
  longline: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    liner:
      - '&0> &0<'
      - '&0> &5&lT&c&lo&e&lp &0<'
      - '&0> &5&lT&c&lo&e&lp &0<'
      - '&0> &5&lT&c&lo&e&lp &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr&b&ls &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr&b&ls &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr&b&ls &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr&b&ls &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr&b&ls &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr&b&ls &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr&b&ls &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le&e&lr &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv&c&le &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr&5&lv &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le&b&lr &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS&c&le &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li&5&lS &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt&e&li &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll&5&lt &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu&c&ll &0<'
      - '&0> &5&lT&c&lo&e&lp&5&lM&a&lu &0<'
      - '&0> &5&lT&c&lo&e&lp &0<'
      - '&0> &5&lT&c&lo &0<'
      - '&0> &5&lT &0<'
      - '&0> &0<'
      - '&0> &0<'

  rows:
    1:
      interval: 80
      liner:
      - '&0&l------------------------'
    2:
      interval: 80
      liner:
      - '&E&lPlayer:'
    3:
      interval: 0
      liner:
      - '% player_name % '
    4:
      interval: 80
      liner:
      - ''
    5:
      interval: 80
      liner:
      - '&b&lRank:'
    6:
      interval: 5
      liner:
      - '%luckperms_primary_group_name%'
    7:
      interval: 80
      liner:
      - ''
    '8':
      interval: 80
      liner:
      - '&cUptime:'
    '9':
      interval: 20
      liner:
      - '%server_uptime%'
    10:
      interval: 80
      liner:
      - ''
    11:
      interval: 80
      liner:
      - '&6&lFASE ALPHA'
    12:
      interval: 80
      liner:
      - '&3&oCreado por Fedes10.'
    50:
      interval: 4
      liner:
      - '&0&l------------------------'